FROM continuumio/anaconda3:2024.10-1

COPY . /usr/app/
WORKDIR /usr/app/

# installing sys level depend. including cuda
RUN apt-get update && apt-get install -y \
    git \
    curl \
    gcc \
    g++ \
    build-essential \
    make \
    cmake \
    wget \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# setup ther requied env
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
ENV CUDA_HOME=/opt/conda
ENV PATH=${CUDA_HOME}/bin:${PATH}
ENV LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}

RUN pip install --upgrade pip

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

RUN pip install -r requirements.txt

RUN pip install vllm --extra-index-url https://download.pytorch.org/whl/cu128
RUN pip install python-dotenv

ENV VLLM_NCCL_SO_PATH=/opt/conda/lib/python3.12/site-packages/vllm/nccl/lib/libnccl.so.2
ENV TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6 8.9 9.0+PTX"

EXPOSE 8709

CMD ["python", "main.py"]