FROM continuumio/anaconda3:2024.10-1

COPY . /usr/app/
WORKDIR /usr/app/

# installing sys level depend
RUN apt-get update && apt-get install -y \
    git \
    curl \
    gcc \
    g++ \
    build-essential \
    make \
    cmake \
    wget \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
ENV CUDA_HOME=/opt/conda
ENV PATH=${CUDA_HOME}/bin:${PATH}
ENV LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}

RUN pip install --upgrade pip

RUN pip install gradio
RUN pip install requests

EXPOSE 8710

CMD ["python", "ui.py"]
